'use strict'

const Event = require('./Event')
const Err = require('./Err')

/**
 * Aggregate base class
 */
module.exports = class Aggregate {
  /**
   * Aggregate factory method
   * @param {Object} aggregateType subclass of Aggregate
   * @param {Object} object with optional payload attributes including _aggregate_id_ and _aggregate_version_
   * @returns {Aggregate} instance of aggregateType
   */
  static create (aggregateType, { _aggregate_id_ = '', _aggregate_version_ = -1, ...payload } = {}) {
    const aggregate = new aggregateType.prototype.constructor()
    Object.assign(aggregate, payload)
    Object.defineProperty(aggregate, '_aggregate_id_', { value: _aggregate_id_, writable: !_aggregate_id_, enumerable: true }) 
    Object.defineProperty(aggregate, '_aggregate_version_', { value: _aggregate_version_, writable: true, enumerable: true })
    Object.defineProperty(aggregate, '_uncommitted_events_', { value: [], writable: false, enumerable: false })
    return aggregate
  }

  get aggregateId () { return this._aggregate_id_ }
  get aggregateVersion () { return this._aggregate_version_ }

  /**
   * Path to collection storing snapshots of this aggregate type.
   * When not provided, aggregate is loaded from events (may cause performance and cost issues when number of events is too large)
   */
  static get path () { return '' }

  /**
   * Name of event stream persisting the events generated by this aggregate. "main" by default
   */
  static get stream () { return 'main' }

  /**
   * Object map of async command handlers receiving actor and payload arguments
   * 
   * Example:
   *    get commands () {
   *      return {
   *        Command1: async (actor, payload) => {
   *          ...
   *        },
   *        Command2: async (actor, payload) => {
   *          ...
   *        }
   *      }
   *    }
   */
  get commands () { throw Err.notImplemented('commands') }

  /**
   * Object map of event handlers receiving event argument
   *
   * Example:
   *    get events () {
   *      return {
   *        ['Event1']: (event) => {
   *          ...
   *        },
   *        ['Event2']: (event) => {
   *          ...
   *        }
   *      }
   *    }
   */
  get events () { throw Err.notImplemented('events') }

  /**
   * Loads event object when replaying aggregate
   * @param {Event} event
   */
  _loadEvent (event) {
    this.events[event.eventName](event)
    this._aggregate_version_++
  }

  /**
   * Event factory method used by command handlers
   * @param {String} name event name
   * @param {Object} payload event payload
   * @param {Integer} version optional event version
   */
  addEvent (name, payload, version = 0) {
    const event = Event.create({ _event_name_: name, _event_version_: version, ...payload })
    this.events[event.eventName](event)
    this._uncommitted_events_.push(event)
  }

  /**
   * Clones aggregate for storage/caching purposes. Override if deep cloning is needed
   * 
   * @returns {Object} Object with aggregate data
   */
  clone () {
    return Object.assign({}, this)
  }
}
